Repository wiremock/WireMock.Net, pull requests merged in 2019-08, with the labels that each got.

#309 Fix LogEntries: collection was modified exception
  Directory.Build.props
  GitHubReleaseNotes.txt
  src/WireMock.Net/IMapping.cs
  src/WireMock.Net/Mapping.cs
  src/WireMock.Net/Owin/WireMockMiddleware.cs
  src/WireMock.Net/Server/FluentMockServer.Admin.cs
  src/WireMock.Net/Server/FluentMockServer.LogEntries.cs
  src/WireMock.Net/Util/CloneUtils.cs
  src/WireMock.Net/WireMock.Net.csproj
Labels: bug

#314 RequestLogExpirationDuration : use DateTime.UtcNow
  src/WireMock.Net/Owin/WireMockMiddleware.cs
Labels: bug

#316 Handles case where parameter value contains ==
  src/WireMock.Net/Util/QueryStringParser.cs
  test/WireMock.Net.Tests/Util/QueryStringParserTests.cs
Labels: feature

#317 Make SaveMapping and SaveMappingToFile settings independent.
  src/WireMock.Net/Server/FluentMockServer.Admin.cs
Labels: feature

#322 Fix MappingMatcher in case of an exception in LinqMatcher.
  src/WireMock.Net/Matchers/LinqMatcher.cs
  src/WireMock.Net/Matchers/XPathMatcher.cs
  src/WireMock.Net/Owin/IMappingMatcher.cs
  src/WireMock.Net/Owin/MappingMatcher.cs
  src/WireMock.Net/Owin/MappingMatcherResult.cs
  src/WireMock.Net/Owin/WireMockMiddleware.cs
  test/WireMock.Net.Tests/Owin/MappingMatcherTests.cs
  test/WireMock.Net.Tests/Owin/WireMockMiddlewareTests.cs
Labels: bug

#323 Refactor MappingConverter & MatcherMapper
  src/WireMock.Net/Serialization/MappingConverter.cs
  src/WireMock.Net/Serialization/MatcherMapper.cs
  src/WireMock.Net/Server/FluentMockServer.Admin.cs
  src/WireMock.Net/Server/FluentMockServer.cs
  test/WireMock.Net.Tests/Serialization/MappingConverterTests.cs
  test/WireMock.Net.Tests/Serialization/MatcherMapperTests.cs
  test/WireMock.Net.Tests/Serialization/MatcherModelMapperTests.cs
Labels: refactor

#326 Fix Parsing Guid in PUT Mapping
  src/WireMock.Net/Server/FluentMockServer.Admin.cs
  test/WireMock.Net.Tests/FluentMockServerAdminRestClientTests.cs
Labels: bug

#331 Fix: Collection was modified exception
  src/WireMock.Net/Server/FluentMockServer.LogEntries.cs
Labels: bug

#328 Fix LogRequest : Index Out Of Bounds
  src/WireMock.Net/Owin/WireMockMiddleware.cs
Labels: bug

#333 JsonMatcher support IgnoreCase
  WireMock.Net Solution.sln
  examples/WireMock.Net.Console.HeadersTest/Program.cs
  examples/WireMock.Net.Console.HeadersTest/WireMock.Net.Console.HeadersTest.csproj
  examples/WireMock.Net.Console.HeadersTest/log4net.config
  examples/WireMock.Net.Console.HeadersTest/nlog.config
  src/WireMock.Net/Matchers/JsonMatcher.cs
  src/WireMock.Net/Serialization/MatcherMapper.cs
  test/WireMock.Net.Tests/Matchers/JsonMatcherTests.cs
Labels: feature

#338 Fix ContentType with parameters in Proxy Mode
  Directory.Build.props
  GitHubReleaseNotes.txt
  src/WireMock.Net/Http/HttpClientHelper.cs
  src/WireMock.Net/Http/HttpRequestMessageHelper.cs
  src/WireMock.Net/Http/HttpResponseMessageHelper.cs
  src/WireMock.Net/Http/StringContentHelper.cs
  src/WireMock.Net/Util/BodyParser.cs
  src/WireMock.Net/WireMock.Net.csproj
  test/WireMock.Net.Tests/Http/HttpRequestMessageHelperTests.cs
  test/WireMock.Net.Tests/Http/StringContentHelperTests.cs
  test/WireMock.Net.Tests/WireMock.Net.Tests.csproj
Labels: bug
