Repository wiremock/WireMock.Net, pull requests merged in 2020-11, with the labels that each got.

#530 Fix dotnet-sonarscanner
  azure-pipelines-ci.yml
Labels: bug

#531 Add WithCallback-Async
  examples/WireMock.Net.Console.Net452.Classic/MainApp.cs
  src/WireMock.Net/ResponseBuilders/ICallbackResponseBuilder.cs
  src/WireMock.Net/ResponseBuilders/Response.WithCallback.cs
  src/WireMock.Net/ResponseBuilders/Response.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithCallbackTests.cs
Labels: feature

#535 WithCallback should use also use enum HttpStatusCode
  src/WireMock.Net/Owin/Mappers/OwinResponseMapper.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithCallbackTests.cs
  test/WireMock.Net.Tests/WireMock.Net.Tests.csproj
  test/WireMock.Net.Tests/WireMockServerTests.WithCallback.cs
  test/WireMock.Net.Tests/WireMockServerTests.cs
Labels: bug

#537 Add Custom Certificate settings
  WireMock.Net Solution.sln
  examples/WireMock.Net.Console.NETCoreApp3WithCertificate/Program.cs
  examples/WireMock.Net.Console.NETCoreApp3WithCertificate/WireMock.Net.Console.NETCoreApp3WithCertificate.csproj
  examples/WireMock.Net.Console.NETCoreApp3WithCertificate/base64_encoded.cer
  examples/WireMock.Net.Console.NETCoreApp3WithCertificate/base64_encoded.privatekey
  examples/WireMock.Net.Console.NETCoreApp3WithCertificate/example.pfx
  src/WireMock.Net/Http/HttpClientHelper.cs
  src/WireMock.Net/HttpsCertificate/CertificateLoader.cs
  src/WireMock.Net/HttpsCertificate/ClientCertificateHelper.cs
  src/WireMock.Net/Owin/AspNetCoreSelfHost.NETStandard.cs
  src/WireMock.Net/Owin/AspNetCoreSelfHost.NETStandard13.cs
  src/WireMock.Net/Owin/AspNetCoreSelfHost.cs
  src/WireMock.Net/Owin/HostUrlDetails.cs
  src/WireMock.Net/Owin/HostUrlOptions.cs
  src/WireMock.Net/Owin/IWireMockMiddlewareOptions.cs
  src/WireMock.Net/Owin/WireMockMiddlewareOptions.cs
  src/WireMock.Net/Server/WireMockServer.cs
  src/WireMock.Net/Settings/IWireMockCertificateSettings.cs
  src/WireMock.Net/Settings/IWireMockServerSettings.cs
  src/WireMock.Net/Settings/WireMockCertificateSettings.cs
  src/WireMock.Net/Settings/WireMockServerSettings.cs
  src/WireMock.Net/Settings/WireMockServerSettingsParser.cs
  src/WireMock.Net/Util/PortUtils.cs
  test/WireMock.Net.Tests/Util/PortUtilsTests.cs
Labels: feature

#529 Add assertions for ClientIP, Url and ProxyUrl
  src/WireMock.Net.FluentAssertions/Assertions/WireMockAssertions.cs
  test/WireMock.Net.Tests/FluentAssertions/WireMockAssertionsTests.cs
Labels: feature

#538 ProxyThisHttps example
  examples/WireMock.Net.Console.Net452.Classic/MainApp.cs
Labels: doc

#542 Create dotnet-wiremock tool
  README.md
  WireMock.Net Solution.sln
  examples/WireMock.Net.StandAlone.NETCoreApp/Program.cs
  examples/WireMock.Net.StandAlone.Net452/Program.cs
  examples/WireMock.Net.StandAlone.Net461/Program.cs
  src/WireMock.Net.Abstractions/WireMock.Net.Abstractions.csproj
  src/WireMock.Net.FluentAssertions/WireMock.Net.FluentAssertions.csproj
  src/WireMock.Net.OpenApiParser/WireMock.Net.OpenApiParser.csproj
  src/WireMock.Net.RestClient/WireMock.Net.RestClient.csproj
  src/WireMock.Net.StandAlone/StandAloneApp.cs
  src/WireMock.Net/Settings/SimpleCommandLineParser.cs
  src/WireMock.Net/Settings/WireMockServerSettingsParser.cs
  src/dotnet-WireMock.Net/Program.cs
  src/dotnet-WireMock.Net/Properties/launchSettings.json
  src/dotnet-WireMock.Net/WireMockLogger.cs
  src/dotnet-WireMock.Net/dotnet-WireMock.csproj
Labels: feature

#543 Add support for .NET 5
  WireMock.Net Solution.sln
  examples/WireMock.Net.Console.NET5/WireMock.Net.Console.NET5.csproj
  examples/WireMock.Net.Console.NET5/__admin/mappings/1.cs
  examples/WireMock.Net.Console.NET5/__admin/mappings/11111110-a633-40e8-a244-5cb80bc0ab66.json
  examples/WireMock.Net.Console.NET5/__admin/mappings/791a3f31-6946-4ce7-8e6f-0237c7443275.json
  examples/WireMock.Net.Console.NET5/__admin/mappings/873d495f-940e-4b86-a1f4-4f0fc7be8b8b.json
  examples/WireMock.Net.Console.NET5/__admin/mappings/BodyAsFileExample.json
  examples/WireMock.Net.Console.NET5/__admin/mappings/MyXmlResponse.xml
  examples/WireMock.Net.Console.NET5/__admin/mappings/array.json
  src/WireMock.Net.StandAlone/WireMock.Net.StandAlone.csproj
  src/WireMock.Net/Http/HttpClientHelper.cs
  src/WireMock.Net/Matchers/CSharpCodeMatcher.cs
  src/WireMock.Net/Owin/AspNetCoreSelfHost.cs
  src/WireMock.Net/WireMock.Net.csproj
  src/dotnet-WireMock.Net/dotnet-WireMock.csproj
Labels: feature

#544 Use Java 11 in Azure Pipelines (needed for SonarCloud)
  azure-pipelines-ci.yml
  test/WireMock.Net.Tests/WireMock.Net.Tests.csproj
Labels: feature

#545 Fix SonarCloud OpenCover (coverlet-coverage)
  .gitignore
  WireMock.Net Solution.sln
  azure-pipelines-ci-linux.yml
  azure-pipelines-ci.yml
  nuget.config
  src/WireMock.Net.StandAlone/StandAloneApp.cs
  src/WireMock.Net/Owin/AspNetCoreSelfHost.cs
  src/WireMock.Net/Server/WireMockServer.cs
  src/WireMock.Net/Settings/WireMockServerSettingsParser.cs
  test/WireMock.Net.Tests/FluentAssertions/WireMockAssertionsTests.cs
  test/WireMock.Net.Tests/ObservableLogEntriesTest.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithBodyFromFileTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithProxyTests.cs
  test/WireMock.Net.Tests/StatefulBehaviorTests.cs
  test/WireMock.Net.Tests/Util/BytesEncodingUtilsTests.cs
  test/WireMock.Net.Tests/WireMock.Net.Tests.csproj
  test/WireMock.Net.Tests/WireMockServer.Admin.cs
  test/WireMock.Net.Tests/WireMockServer.Authentication.cs
  test/WireMock.Net.Tests/WireMockServer.Proxy.cs
  test/WireMock.Net.Tests/WireMockServerTests.WithCallback.cs
  test/WireMock.Net.Tests/WireMockServerTests.cs
  test/WireMock.Net.Tests/WithMapping/WireMockServerWithMappingTests.cs
Labels: bug
