Repository wiremock/WireMock.Net, pull requests merged in 2020-03, with the labels that each got.

#427 Add UsingOptions, UsingConnect and UsingTrace
  src/WireMock.Net/Http/HttpRequestMethods.cs
  src/WireMock.Net/RequestBuilders/IMethodRequestBuilder.cs
  src/WireMock.Net/RequestBuilders/Request.UsingMethods.cs
  src/WireMock.Net/RequestBuilders/Request.cs
  src/WireMock.Net/Util/BodyParser.cs
  test/WireMock.Net.Tests/RequestBuilders/RequestBuilderUsingMethodTests.cs
Labels: feature

#434 Option to disable JSON deserialization
  src/WireMock.Net/Http/HttpClientHelper.cs
  src/WireMock.Net/Http/HttpResponseMessageHelper.cs
  src/WireMock.Net/Owin/IWireMockMiddlewareOptions.cs
  src/WireMock.Net/Owin/Mappers/OwinRequestMapper.cs
  src/WireMock.Net/Owin/WireMockMiddlewareOptions.cs
  src/WireMock.Net/ResponseBuilders/Response.cs
  src/WireMock.Net/Server/WireMockServer.Admin.cs
  src/WireMock.Net/Server/WireMockServer.cs
  src/WireMock.Net/Settings/IWireMockServerSettings.cs
  src/WireMock.Net/Settings/WireMockServerSettings.cs
  src/WireMock.Net/Settings/WireMockServerSettingsParser.cs
  src/WireMock.Net/Util/BodyParser.cs
  test/WireMock.Net.Tests/RequestMatchers/RequestMessageBodyMatcherTests.cs
  test/WireMock.Net.Tests/Util/BodyParserTests.cs
Labels: feature

#435 Also call HandlebarsRegistrationCallback when using WithCallback(..)
  src/WireMock.Net/ResponseBuilders/Response.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithCallbackTests.cs
Labels: feature

#417 Let the .NET core/standard WebHostBuilder use a random port
  src/WireMock.Net/Owin/AspNetCoreSelfHost.cs
  src/WireMock.Net/Owin/HostUrlOptions.cs
  src/WireMock.Net/Owin/OwinSelfHost.cs
  src/WireMock.Net/Server/WireMockServer.cs
  test/WireMock.Net.Tests/ObservableLogEntriesTest.cs
  test/WireMock.Net.Tests/WireMock.Net.Tests.csproj
Labels: bug

#422 AllowOnlyDefinedHttpStatusCodeInResponse
  Directory.Build.props
  examples/WireMock.Net.Console.Net452.Classic/MainApp.cs
  src/WireMock.Net/Owin/IWireMockMiddlewareOptions.cs
  src/WireMock.Net/Owin/Mappers/OwinResponseMapper.cs
  src/WireMock.Net/Owin/WireMockMiddlewareOptions.cs
  src/WireMock.Net/ResponseBuilders/IStatusCodeResponseBuilder.cs
  src/WireMock.Net/Server/WireMockServer.cs
  src/WireMock.Net/Settings/IWireMockServerSettings.cs
  src/WireMock.Net/Settings/WireMockServerSettings.cs
  src/WireMock.Net/Settings/WireMockServerSettingsParser.cs
  test/WireMock.Net.Tests/Owin/Mappers/OwinResponseMapperTests.cs
  test/WireMock.Net.Tests/WireMock.Net.Tests.csproj
  test/WireMock.Net.Tests/WireMockServer.Settings.cs
Labels: bug

#440 Add .net 472 example for WireMock.Net.RestClient
  WireMock.Net Solution.sln
  examples/WireMock.Net.Client.Net472/App.config
  examples/WireMock.Net.Client.Net472/Program.cs
  examples/WireMock.Net.Client.Net472/Properties/AssemblyInfo.cs
  examples/WireMock.Net.Client.Net472/WireMock.Net.Client.Net472.csproj
  examples/WireMock.Net.Client.Net472/packages.config
Labels: doc

#442 Fix Null body in handlebars transformation
  Directory.Build.props
  src/WireMock.Net/Transformers/ResponseMessageTransformer.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsTests.cs
Labels: bug

#446 When port is provided: WireMockServer still takes a random port
  examples/WireMock.Net.StandAlone.NETCoreApp/Properties/launchSettings.json
  src/WireMock.Net/Owin/AspNetCoreSelfHost.cs
  src/WireMock.Net/Owin/HostUrlOptions.cs
  src/WireMock.Net/Server/WireMockServer.cs
Labels: bug
