Repository wiremock/WireMock.Net, pull requests merged in 2020-07, with the labels that each got.

#479 An OpenApi (swagger) parser to generate MappingModel or mapping.json file
  WireMock.Net Solution.sln
  examples/WireMock.Net.Client/WireMock.Net.Client.csproj
  examples/WireMock.Net.Console.NETCoreApp2/Program.cs
  examples/WireMock.Net.Console.NETCoreApp2/WireMock.Net.Console.NETCoreApp2.csproj
  examples/WireMock.Net.Console.NETCoreApp2/__admin/mappings/wiremock-petstore-openapi3.json
  examples/WireMock.Net.OpenApiParser.ConsoleApp/Program.cs
  examples/WireMock.Net.OpenApiParser.ConsoleApp/Run.cs
  examples/WireMock.Net.OpenApiParser.ConsoleApp/WireMock.Net.OpenApiParser.ConsoleApp.csproj
  examples/WireMock.Net.OpenApiParser.ConsoleApp/infura.yaml
  examples/WireMock.Net.OpenApiParser.ConsoleApp/petstore-openapi3.json
  examples/WireMock.Net.OpenApiParser.ConsoleApp/petstore.yml
  examples/WireMock.Net.OpenApiParser.ConsoleApp/wiremock-petstore-openapi3.json
  src/WireMock.Net.Abstractions/Server/IWireMockServer.cs
  src/WireMock.Net.Abstractions/WireMock.Net.Abstractions.csproj
  src/WireMock.Net.OpenApiParser/Extensions/OpenApiSchemaExtensions.cs
  src/WireMock.Net.OpenApiParser/Extensions/WireMockServerExtensions.cs
  src/WireMock.Net.OpenApiParser/IWireMockOpenApiParser.cs
  src/WireMock.Net.OpenApiParser/Types/SchemaFormat.cs
  src/WireMock.Net.OpenApiParser/Types/SchemaType.cs
  src/WireMock.Net.OpenApiParser/Utils/DateTimeUtils.cs
  src/WireMock.Net.OpenApiParser/Utils/ExampleValueGenerator.cs
  src/WireMock.Net.OpenApiParser/WireMock.Net.OpenApiParser.csproj
  src/WireMock.Net.OpenApiParser/WireMockOpenApiParser.cs
  src/WireMock.Net.StandAlone/WireMock.Net.StandAlone.csproj
  src/WireMock.Net/Server/WireMockServer.Admin.cs
  src/WireMock.Net/Server/WireMockServer.LogEntries.cs
  src/WireMock.Net/Server/WireMockServer.cs
  src/WireMock.Net/WireMock.Net.csproj
  test/WireMock.Net.Tests/WireMockAdminApiTests.cs
  test/WireMock.Net.Tests/WireMockServerTests.cs
  test/WireMock.Net.Tests/WithMapping/WireMockServerWithMappingTests.cs
Labels: feature

#482 Add PartialMatch to logging / logentries
  WireMock.Net Solution.sln
  src/WireMock.Net.Abstractions/Admin/Requests/LogEntryModel.cs
  src/WireMock.Net.FluentAssertions/Assertions/WireMockANumberOfCallsAssertions.cs
  src/WireMock.Net.FluentAssertions/Assertions/WireMockAssertions.cs
  src/WireMock.Net.FluentAssertions/Assertions/WireMockReceivedAssertions.cs
  src/WireMock.Net.FluentAssertions/Extensions/WireMockExtensions.cs
  src/WireMock.Net.FluentAssertions/WireMock.Net.FluentAssertions.csproj
  src/WireMock.Net/Logging/LogEntry.cs
  src/WireMock.Net/Owin/IMappingMatcher.cs
  src/WireMock.Net/Owin/MappingMatcher.cs
  src/WireMock.Net/Owin/WireMockMiddleware.cs
  src/WireMock.Net/Serialization/LogEntryMapper.cs
  test/WireMock.Net.Tests/Owin/MappingMatcherTests.cs
  test/WireMock.Net.Tests/Owin/WireMockMiddlewareTests.cs
Labels: feature

#484 Refactor: extract interfaces
  examples/WireMock.Net.WebApplication/WireMockService.cs
  src/WireMock.Net.Abstractions/IRequestMessage.cs
  src/WireMock.Net.Abstractions/IResponseMessage.cs
  src/WireMock.Net.Abstractions/Logging/ILogEntry.cs
  src/WireMock.Net.Abstractions/Matchers/Request/IRequestMatchResult.cs
  src/WireMock.Net.Abstractions/Matchers/Request/MatchDetail.cs
  src/WireMock.Net.Abstractions/ResponseBuilders/FaultType.cs
  src/WireMock.Net.Abstractions/Server/IWireMockServer.cs
  src/WireMock.Net.Abstractions/Util/IBodyData.cs
  src/WireMock.Net.FluentAssertions/Assertions/WireMockANumberOfCallsAssertions.cs
  src/WireMock.Net.FluentAssertions/Assertions/WireMockAssertions.cs
  src/WireMock.Net.FluentAssertions/Assertions/WireMockReceivedAssertions.cs
  src/WireMock.Net.FluentAssertions/Extensions/WireMockExtensions.cs
  src/WireMock.Net.FluentAssertions/WireMock.Net.FluentAssertions.csproj
  src/WireMock.Net/IMapping.cs
  src/WireMock.Net/Logging/LogEntry.cs
  src/WireMock.Net/Matchers/Request/IRequestMatcher.cs
  src/WireMock.Net/Matchers/Request/RequestMatchResult.cs
  src/WireMock.Net/Matchers/Request/RequestMessageBodyMatcher.cs
  src/WireMock.Net/Matchers/Request/RequestMessageClientIPMatcher.cs
  src/WireMock.Net/Matchers/Request/RequestMessageCompositeMatcher.cs
  src/WireMock.Net/Matchers/Request/RequestMessageCookieMatcher.cs
  src/WireMock.Net/Matchers/Request/RequestMessageHeaderMatcher.cs
  src/WireMock.Net/Matchers/Request/RequestMessageMethodMatcher.cs
  src/WireMock.Net/Matchers/Request/RequestMessageParamMatcher.cs
  src/WireMock.Net/Matchers/Request/RequestMessagePathMatcher.cs
  src/WireMock.Net/Matchers/Request/RequestMessageScenarioAndStateMatcher.cs
  src/WireMock.Net/Matchers/Request/RequestMessageUrlMatcher.cs
  src/WireMock.Net/RequestMessage.cs
  src/WireMock.Net/ResponseMessage.cs
  src/WireMock.Net/Serialization/LogEntryMapper.cs
  src/WireMock.Net/Server/WireMockServer.Admin.cs
  src/WireMock.Net/Server/WireMockServer.LogEntries.cs
  src/WireMock.Net/Util/BodyData.cs
Labels: feature

#487 Fixed MappingConverter when methods are null
  src/WireMock.Net/Serialization/MappingConverter.cs
  test/WireMock.Net.Tests/WireMockAdminApiTests.cs
Labels: bug

#485 Add fluent assertions for headers
  src/WireMock.Net.FluentAssertions/Assertions/WireMockAssertions.cs
  test/WireMock.Net.Tests/FluentAssertions/WireMockAssertionsTests.cs
Labels: test

#492 Mark FluentMockServer, FluentMockServerSettings, BlacklistedHeaders and BlacklistedCookies as obsolete
  src/WireMock.Net.StandAlone/StandAloneApp.cs
  src/WireMock.Net/Server/FluentMockServer.cs
  src/WireMock.Net/Server/WireMockServer.Admin.cs
  src/WireMock.Net/Settings/FluentMockServerSettings.cs
  src/WireMock.Net/Settings/IFluentMockServerSettings.cs
  src/WireMock.Net/Settings/IProxyAndRecordSettings.cs
  src/WireMock.Net/Settings/ProxyAndRecordSettings.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithStatusCodeTests.cs
  test/WireMock.Net.Tests/WireMockServer.Proxy.cs
Labels: feature
