Repository wiremock/WireMock.Net, pull requests merged in 2021-03, with the labels that each got.

#594 Add possibility to the WithBody() to use IBodyData
  examples/WireMock.Net.StandAlone.NETCoreApp/Program.cs
  src/WireMock.Net/Matchers/Request/RequestMessageBodyMatcher.cs
  src/WireMock.Net/RequestBuilders/IBodyRequestBuilder.cs
  src/WireMock.Net/RequestBuilders/Request.WithBody.cs
  test/WireMock.Net.Tests/RequestWithBodyTests.cs
Labels: feature

#595 Use Handlebars.Net.Helpers Version="2.1.2"
  src/WireMock.Net/WireMock.Net.csproj
Labels: feature

#597 Remove 2 second delay from first response and add IPv6 address support
  src/WireMock.Net/Owin/AspNetCoreSelfHost.NETStandard.cs
  src/WireMock.Net/Owin/AspNetCoreSelfHost.cs
  test/WireMock.Net.Tests/WireMockServerTests.cs
Labels: bug, feature

#591 Webhook
  examples/WireMock.Net.StandAlone.NETCoreApp/Program.cs
  examples/WireMock.Net.StandAlone.NETCoreApp/Properties/launchSettings.json
  src/WireMock.Net.Abstractions/Admin/Mappings/MappingModel.cs
  src/WireMock.Net.Abstractions/Admin/Mappings/ResponseModel.cs
  src/WireMock.Net.Abstractions/Admin/Mappings/WebhookModel.cs
  src/WireMock.Net.Abstractions/Admin/Mappings/WebhookRequestModel.cs
  src/WireMock.Net.Abstractions/Models/IBodyData.cs
  src/WireMock.Net.Abstractions/Models/IWebhook.cs
  src/WireMock.Net.Abstractions/Models/IWebhookRequest.cs
  src/WireMock.Net/Http/HttpClientBuilder.cs
  src/WireMock.Net/Http/WebhookSender.cs
  src/WireMock.Net/IMapping.cs
  src/WireMock.Net/Mapping.cs
  src/WireMock.Net/Models/BodyData.cs
  src/WireMock.Net/Models/Webhook.cs
  src/WireMock.Net/Models/WebhookRequest.cs
  src/WireMock.Net/Owin/Mappers/OwinRequestMapper.cs
  src/WireMock.Net/Owin/WireMockMiddleware.cs
  src/WireMock.Net/Proxy/ProxyHelper.cs
  src/WireMock.Net/RequestMessage.cs
  src/WireMock.Net/Serialization/MappingConverter.cs
  src/WireMock.Net/Serialization/WebhookMapper.cs
  src/WireMock.Net/Server/IRespondWithAProvider.cs
  src/WireMock.Net/Server/RespondWithAProvider.cs
  src/WireMock.Net/Server/WireMockServer.Admin.cs
  src/WireMock.Net/Settings/HttpClientSettings.cs
  src/WireMock.Net/Settings/IHttpClientSettings.cs
  src/WireMock.Net/Settings/IProxyAndRecordSettings.cs
  src/WireMock.Net/Settings/IWebhookSettings.cs
  src/WireMock.Net/Settings/IWireMockServerSettings.cs
  src/WireMock.Net/Settings/ProxyAndRecordSettings.cs
  src/WireMock.Net/Settings/WebhookSettings.cs
  src/WireMock.Net/Settings/WireMockServerSettings.cs
  src/WireMock.Net/Transformers/ITransformer.cs
  src/WireMock.Net/Transformers/Transformer.cs
  test/WireMock.Net.Tests/Serialization/MappingConverterTests.cs
  test/WireMock.Net.Tests/Serialization/WebhookMapperTests.cs
  test/WireMock.Net.Tests/WireMockServer.WebhookTests.cs
Labels: feature

#600 WithProxy() should save the new mapping
  WireMock.Net Solution.sln
  examples/WireMock.Net.Service/WireMock.Net.Service.csproj
  examples/WireMock.Net.Service/packages.config
  examples/WireMock.Net.StandAlone.Net452/WireMock.Net.StandAlone.Net452.csproj
  examples/WireMock.Net.StandAlone.Net452/packages.config
  src/WireMock.Net/IMapping.cs
  src/WireMock.Net/Mapping.cs
  src/WireMock.Net/Models/BodyData.cs
  src/WireMock.Net/Owin/WireMockMiddleware.cs
  src/WireMock.Net/Proxy/ProxyHelper.cs
  src/WireMock.Net/ResponseBuilders/Response.cs
  src/WireMock.Net/ResponseProviders/DynamicAsyncResponseProvider.cs
  src/WireMock.Net/ResponseProviders/DynamicResponseProvider.cs
  src/WireMock.Net/ResponseProviders/IResponseProvider.cs
  src/WireMock.Net/ResponseProviders/ProxyAsyncResponseProvider.cs
  test/WireMock.Net.Tests/Owin/WireMockMiddlewareTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseCreateTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithBodyTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithCallbackTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithFaultTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsFileTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsHelpersTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsJsonPathTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsLinqTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsRandomTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsRegexTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsXPathTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsXegerTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHeadersTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithProxyTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithScribanTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithStatusCodeTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithTransformerTests.cs
  test/WireMock.Net.Tests/WireMockAdminApiTests.cs
Labels: bug
