Repository wiremock/WireMock.Net, pull requests merged in 2023-03, with the labels that each got.

#900 ProxySettings : Add logic to not save some requests depending on HttpMethods
  src/WireMock.Net/Matchers/MatchScores.cs
  src/WireMock.Net/Proxy/ProxyHelper.cs
  src/WireMock.Net/Serialization/ProxyMappingConverter.cs
  src/WireMock.Net/Settings/ProxyAndRecordSettings.cs
  src/WireMock.Net/Settings/ProxySaveMappingSetting.cs
  src/WireMock.Net/Settings/ProxySaveMappingSettings.cs
  src/WireMock.Net/Settings/WireMockServerSettingsParser.cs
  test/WireMock.Net.Tests/Serialization/ProxyMappingConverterTests.cs
  test/WireMock.Net.Tests/WireMockServer.Proxy.cs
Labels: feature

#893 Add 'Data' to response which can be used during transforming the response
  examples/WireMock.Net.Console.NET6/WireMock.Net.Console.NET6.csproj
  src/WireMock.Net.Abstractions/Admin/Mappings/MappingModel.cs
  src/WireMock.Net.Abstractions/Admin/Mappings/ResponseModel.cs
  src/WireMock.Net.Abstractions/IResponseMessage.cs
  src/WireMock.Net/IMapping.cs
  src/WireMock.Net/Json/DynamicJsonClassOptions.cs
  src/WireMock.Net/Json/DynamicPropertyWithValue.cs
  src/WireMock.Net/Json/FloatBehavior.cs
  src/WireMock.Net/Json/IntegerBehavior.cs
  src/WireMock.Net/Json/JObjectExtensions.cs
  src/WireMock.Net/Mapping.cs
  src/WireMock.Net/Matchers/LinqMatcher.cs
  src/WireMock.Net/ResponseBuilders/Response.cs
  src/WireMock.Net/Serialization/MappingConverter.cs
  src/WireMock.Net/Serialization/ProxyMappingConverter.cs
  src/WireMock.Net/Server/IRespondWithAProvider.cs
  src/WireMock.Net/Server/RespondWithAProvider.cs
  src/WireMock.Net/Server/WireMockServer.ConvertMapping.cs
  src/WireMock.Net/Transformers/TransformModel.cs
  src/WireMock.Net/Transformers/Transformer.cs
  src/WireMock.Net/Util/JsonUtils.cs
  src/WireMock.Net/WireMock.Net.csproj
  test/WireMock.Net.Tests/Owin/WireMockMiddlewareTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsLinqTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithTransformerTests.cs
  test/WireMock.Net.Tests/Serialization/MappingConverterTests.ToCSharpCode.cs
  test/WireMock.Net.Tests/Serialization/MappingConverterTests.cs
  test/WireMock.Net.Tests/WireMock.Net.Tests.csproj
Labels: feature

#904 Update Handlebars.Net.Helpers to 2.3.15
  src/WireMock.Net/WireMock.Net.csproj
  test/WireMock.Net.Tests/WireMock.Net.Tests.csproj
Labels: feature

#903 Add WithBody with IDictionary (form-urlencoded values)
  src/WireMock.Net.Abstractions/Models/IBodyData.cs
  src/WireMock.Net.Abstractions/Types/BodyType.cs
  src/WireMock.Net/Matchers/Request/RequestMessageBodyMatcher.cs
  src/WireMock.Net/Models/BodyData.cs
  src/WireMock.Net/RequestBuilders/IBodyRequestBuilder.cs
  src/WireMock.Net/RequestBuilders/Request.WithBody.cs
  src/WireMock.Net/Util/BodyParser.cs
  src/WireMock.Net/Util/BodyParserSettings.cs
  src/WireMock.Net/Util/QueryStringParser.cs
  test/WireMock.Net.Tests/RequestMatchers/RequestMessageBodyMatcherTests.cs
  test/WireMock.Net.Tests/RequestWithBodyTests.cs
  test/WireMock.Net.Tests/Util/QueryStringParserTests.cs
  test/WireMock.Net.Tests/WireMockServerTests.WithBody.cs
Labels: feature

#905 Add DeserializeFormUrl Encoded to the settings
  src/WireMock.Net.Abstractions/Admin/Settings/SettingsModel.cs
  src/WireMock.Net/Http/HttpResponseMessageHelper.cs
  src/WireMock.Net/Json/JObjectExtensions.cs
  src/WireMock.Net/Matchers/NotNullOrEmptyMatcher.cs
  src/WireMock.Net/Proxy/ProxyHelper.cs
  src/WireMock.Net/Serialization/MappingConverter.cs
  src/WireMock.Net/Server/WireMockServer.Admin.cs
  src/WireMock.Net/Settings/ProxySaveMappingSetting.cs
  src/WireMock.Net/Settings/SimpleCommandLineParser.cs
  src/WireMock.Net/Settings/WireMockServerSettings.cs
  src/WireMock.Net/Settings/WireMockServerSettingsParser.cs
  src/WireMock.Net/Util/HttpStatusRangeParser.cs
  src/WireMock.Net/Util/RegexUtils.cs
  src/WireMock.Net/Util/TypeBuilderUtils.cs
  src/WireMock.Net/Validation/ValidatedNotNullAttribute.cs
  test/WireMock.Net.Tests/Matchers/JmesPathMatcherTests.cs
  test/WireMock.Net.Tests/Matchers/JsonMatcherTests.cs
  test/WireMock.Net.Tests/Matchers/JsonPartialMatcherTests.cs
  test/WireMock.Net.Tests/Matchers/JsonPartialWildcardMatcherTests.cs
  test/WireMock.Net.Tests/Matchers/JsonPathMatcherTests.cs
Labels: feature

#907 Fix issue with application/x-www-form-urlencoded and ExactMatcher
  src/WireMock.Net/Http/HttpRequestMessageHelper.cs
  src/WireMock.Net/Matchers/Request/RequestMessageBodyMatcher.cs
  src/WireMock.Net/Owin/Mappers/OwinResponseMapper.cs
  src/WireMock.Net/Serialization/LogEntryMapper.cs
  src/WireMock.Net/Serialization/MappingConverter.cs
  src/WireMock.Net/Serialization/ProxyMappingConverter.cs
  src/WireMock.Net/Serialization/WebhookMapper.cs
  src/WireMock.Net/Server/WireMockServer.Admin.cs
  src/WireMock.Net/Server/WireMockServer.AdminFiles.cs
  src/WireMock.Net/Transformers/Transformer.cs
  test/WireMock.Net.Tests/WireMockServerTests.WithBody.cs
Labels: bug

#908 RequestBuilder : add WithBodyAsJson and WithBody (with IJsonConverter)
  src/WireMock.Net/RequestBuilders/IBodyRequestBuilder.cs
  src/WireMock.Net/RequestBuilders/Request.WithBody.cs
  src/WireMock.Net/ResponseBuilders/IBodyResponseBuilder.cs
  test/WireMock.Net.Tests/RequestWithBodyTests.cs
Labels: feature

#911 Fixed QueryStringParser for UrlEncoded values
  src/WireMock.Net/Util/QueryStringParser.cs
  test/WireMock.Net.Tests/Util/QueryStringParserTests.cs
Labels: bug

#913 Update comments for models
  src/WireMock.Net.Abstractions/Admin/Mappings/CookieModel.cs
  src/WireMock.Net.Abstractions/Admin/Mappings/HeaderModel.cs
Labels: doc

#914 #912 add excluded params to proxy mapping
  src/WireMock.Net/Serialization/ProxyMappingConverter.cs
  src/WireMock.Net/Settings/ProxyAndRecordSettings.cs
  test/WireMock.Net.Tests/WireMockServer.Proxy.cs
Labels: feature
