Repository wiremock/WireMock.Net, pull requests merged in 2023-01, with the labels that each got.

#871 Add UseWebhooksFireAndForget to Server ConvertMapping
  src/WireMock.Net/Server/WireMockServer.ConvertMapping.cs
Labels: bug

#869 Add MappingBuilder to build mappings in code and export to Models or JSON
  examples/WireMock.Net.Console.Net452.Classic/MainApp.cs
  src/WireMock.Net/IMappingBuilder.cs
  src/WireMock.Net/MappingBuilder.cs
  src/WireMock.Net/Owin/WireMockMiddlewareOptionsHelper.cs
  src/WireMock.Net/Serialization/MappingToFileSaver.cs
  src/WireMock.Net/Serialization/MatcherMapper.cs
  src/WireMock.Net/Server/WireMockServer.Admin.cs
  src/WireMock.Net/Server/WireMockServer.cs
  test/WireMock.Net.Tests/Handlers/LocalFileSystemHandlerTests.cs
  test/WireMock.Net.Tests/MappingBuilderTests.cs
Labels: feature

#877 Add unit test example for Transformer Handlebars String.Append String.Join
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithTransformerTests.cs
Labels: test
