Repository wiremock/WireMock.Net, pull requests merged in 2023-05, with the labels that each got.

#930 Update C# mapping code generator for WithStatusCode
  src/WireMock.Net/Serialization/MappingConverter.cs
  test/WireMock.Net.Tests/WireMockAdminApiTests.IWireMockAdminApi_GetMappingsCode.verified.txt
  test/WireMock.Net.Tests/WireMockAdminApiTests.cs
Labels: feature

#931 Add property 'IsStartedWithAdminInterface' to 'IWireMockServer'
  src/WireMock.Net.Abstractions/Server/IWireMockServer.cs
  src/WireMock.Net/Server/WireMockServer.cs
  test/WireMock.Net.Tests/WireMockServerTests.cs
Labels: feature

#932 Add Package Readme
  Directory.Build.props
  PackageReadme.md
  README.md
  WireMock.Net Solution.sln
Labels: doc

#934 Code generator improvements
  src/WireMock.Net/Serialization/MappingConverter.cs
  src/WireMock.Net/Util/CSharpFormatter.cs
  test/WireMock.Net.Tests/WireMockAdminApiTests.IWireMockAdminApi_GetMappingsCode.verified.txt
  test/WireMock.Net.Tests/WireMockAdminApiTests.cs
Labels: feature

#938 Add more unitests for CSharpFormatter utils
  src/WireMock.Net/Util/CSharpFormatter.cs
  test/WireMock.Net.Tests/Util/BytesEncodingUtilsTests.cs
  test/WireMock.Net.Tests/Util/CSharpFormatterTests.cs
Labels: test

#939 WireMockMiddleware should use HandleRequestsSynchronously correctly
  src/WireMock.Net/Owin/WireMockMiddleware.cs
Labels: bug

#944 Update Slack link
  README.md
Labels: doc

#946 Add warning logging when sending a request to a Webhook does not return status 200
  src/WireMock.Net/.filenesting.json
  src/WireMock.Net/Owin/WireMockMiddleware.cs
  test/WireMock.Net.Tests/WireMockServer.WebhookTests.cs
Labels: feature
