Repository wiremock/WireMock.Net, pull requests merged in 2023-12, with the labels that each got.

#1018 Add .NET 8
  .github/workflows/CreateRelease.yml
  CHANGELOG.md
  WireMock.Net Solution.sln
  azure-pipelines-ci-linux.yml
  azure-pipelines-ci.yml
  azure-pipelines-linux.yml
  azure-pipelines-nuget.yml
  examples/WireMock.Net.Console.NET8/WireMock.Net.Console.NET8.csproj
  examples/WireMock.Net.Console.NET8/__admin/mappings/1.cs
  examples/WireMock.Net.Console.NET8/__admin/mappings/11111110-a633-40e8-a244-5cb80bc0ab66.json
  examples/WireMock.Net.Console.NET8/__admin/mappings/791a3f31-6946-4ce7-8e6f-0237c7443275.json
  examples/WireMock.Net.Console.NET8/__admin/mappings/873d495f-940e-4b86-a1f4-4f0fc7be8b8b.json
  examples/WireMock.Net.Console.NET8/__admin/mappings/BodyAsFileExample.json
  examples/WireMock.Net.Console.NET8/__admin/mappings/MyXmlResponse.xml
  examples/WireMock.Net.Console.NET8/__admin/mappings/array.json
  examples/WireMock.Net.Console.NET8/__admin/mappings/issue-1001.json
  examples/WireMock.Net.Console.NET8/log4net.config
  examples/WireMock.Net.StandAlone.NETCoreApp/Program.cs
  examples/WireMock.Net.StandAlone.NETCoreApp/Properties/launchSettings.json
  examples/WireMock.Net.StandAlone.NETCoreApp/WireMock.Net.StandAlone.NETCoreApp.csproj
  examples/WireMock.Net.StandAlone.NETCoreApp/WireMockLog4NetLogger.cs
  examples/WireMock.Net.StandAlone.Net452/Program.cs
  examples/WireMock.Net.StandAlone.Net452/Properties/AssemblyInfo.cs
  examples/WireMock.Net.StandAlone.Net452/WireMock.Net.StandAlone.Net452.csproj
  examples/WireMock.Net.StandAlone.Net452/app.config
  examples/WireMock.Net.StandAlone.Net452/log4net.config
  examples/WireMock.Net.StandAlone.Net452/packages.config
  examples/WireMock.Net.StandAlone.Net461/App.config
  examples/WireMock.Net.StandAlone.Net461/Program.cs
  examples/WireMock.Net.StandAlone.Net461/Properties/AssemblyInfo.cs
  examples/WireMock.Net.StandAlone.Net461/WireMock.Net.StandAlone.Net461.csproj
  examples/WireMock.Net.StandAlone.Net461/packages.config
  examples/WireMock.Net.TestcontainersExample/WireMock.Net.TestcontainersExample.csproj
  src/WireMock.Net.Abstractions/WireMock.Net.Abstractions.csproj
  src/WireMock.Net.FluentAssertions/WireMock.Net.FluentAssertions.csproj
  src/WireMock.Net.Matchers.CSharpCode/Matchers/CSharpCodeMatcher.cs
  src/WireMock.Net.Matchers.CSharpCode/WireMock.Net.Matchers.CSharpCode.csproj
  src/WireMock.Net.OpenApiParser/WireMock.Net.OpenApiParser.csproj
  src/WireMock.Net.StandAlone/WireMock.Net.StandAlone.csproj
  src/WireMock.Net.Testcontainers/WireMock.Net.Testcontainers.csproj
  src/WireMock.Net/Http/HttpClientBuilder.cs
  src/WireMock.Net/Owin/AspNetCoreSelfHost.NETCore.cs
  src/WireMock.Net/Owin/AspNetCoreSelfHost.cs
  src/WireMock.Net/WireMock.Net.csproj
  src/WireMock.Org.Abstractions/WireMock.Org.Abstractions.csproj
  src/dotnet-WireMock.Net/dotnet-WireMock.csproj
  test/WireMock.Net.Tests/WireMock.Net.Tests.csproj
  test/WireMock.Net.Tests/WireMockServerTests.cs
Labels: feature

#1023 Fix Mapping[] for WireMock.Org REST API
  src/WireMock.Net/Server/WireMockServer.ImportWireMockOrg.cs
  src/WireMock.Org.Abstractions/GetAdminMappingsResult.cs
  src/WireMock.Org.Abstractions/Mapping.cs
  src/WireMock.Org.Abstractions/Mappings.cs
  src/WireMock.Org.Abstractions/PostAdminMappingsFindByMetadataResult.cs
  src/WireMock.Org.Abstractions/PostAdminRecordingsSnapshotResult.cs
  src/WireMock.Org.Abstractions/PostAdminRecordingsStopResult.cs
  src/WireMock.Org.RestClient/IWireMockOrgApi.cs
Labels: bug

#1029 Add ResponseWithHandlebarsDateTimeTests
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsDateTimeTests.cs
Labels: test

#1031 Calling Reset also resets the scenarios
  src/WireMock.Net.Abstractions/Server/IWireMockServer.cs
  src/WireMock.Net/Server/WireMockServer.cs
Labels: bug

#1034 Workaround for: Random.Generate Type="Long"
  src/WireMock.Net/Transformers/Transformer.cs
  src/WireMock.Net/WireMock.Net.csproj
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsRandomTests.cs
Labels: bug

#1026 Add ProxyUrlReplaceSettings to Response
  examples/WireMock.Net.Console.Net452.Classic/MainApp.cs
  src/WireMock.Net.Abstractions/Admin/Mappings/ResponseModel.cs
  src/WireMock.Net.Abstractions/Admin/Settings/ProxyAndRecordSettingsModel.cs
  src/WireMock.Net.Abstractions/Admin/Settings/WebProxySettings.cs
  src/WireMock.Net/Serialization/MappingConverter.cs
  src/WireMock.Net/Server/WireMockServer.ConvertMapping.cs
  src/WireMock.Net/Util/TinyMapperUtils.cs
  test/WireMock.Net.Tests/WireMockAdminApiTests.IWireMockAdminApi_GetMappingAsync_WithProxy_And_ProxyUrlReplaceSettings.verified.txt
  test/WireMock.Net.Tests/WireMockAdminApiTests.cs
Labels: feature

#1038 Proxy all requests - even a repeated one
  src/WireMock.Net.Abstractions/Admin/Settings/ProxyAndRecordSettingsModel.cs
  src/WireMock.Net/Owin/IWireMockMiddlewareOptions.cs
  src/WireMock.Net/Owin/WireMockMiddlewareOptions.cs
  src/WireMock.Net/Server/WireMockServer.Proxy.cs
  src/WireMock.Net/Settings/ProxyAndRecordSettings.cs
  src/WireMock.Net/Settings/WireMockServerSettingsParser.cs
  test/WireMock.Net.Tests/WireMockServer.Proxy.cs
Labels: feature

#1036 Update Handlebars Transformer logic (ReplaceNodeOptions)
  WireMock.Net Solution.sln
  examples/WireMock.Net.Console.NET5/WireMock.Net.Console.NET5.csproj
  examples/WireMock.Net.Console.NET7.UsingNuGet/WireMock.Net.Console.NET7.UsingNuGet.csproj
  examples/WireMock.Net.Console.NETCoreApp/WireMock.Net.Console.NETCoreApp.csproj
  examples/WireMock.Net.Console.NETCoreApp2/Program.cs
  examples/WireMock.Net.Console.NETCoreApp2/WireMock.Net.Console.NETCoreApp2.csproj
  examples/WireMock.Net.Console.NETCoreApp2/__admin/mappings/1.cs
  examples/WireMock.Net.Console.NETCoreApp2/__admin/mappings/11111110-a633-40e8-a244-5cb80bc0ab66.json
  examples/WireMock.Net.Console.NETCoreApp2/__admin/mappings/791a3f31-6946-4ce7-8e6f-0237c7443275.json
  examples/WireMock.Net.Console.NETCoreApp2/__admin/mappings/873d495f-940e-4b86-a1f4-4f0fc7be8b8b.json
  examples/WireMock.Net.Console.NETCoreApp2/__admin/mappings/BodyAsFileExample.json
  examples/WireMock.Net.Console.NETCoreApp2/__admin/mappings/MyXmlResponse.xml
  examples/WireMock.Net.Console.NETCoreApp2/__admin/mappings/array.json
  examples/WireMock.Net.Console.NETCoreApp2/__admin/mappings/wiremock-petstore-openapi3.json
  examples/WireMock.Net.Console.NETCoreApp3/WireMock.Net.Console.NETCoreApp3.csproj
  examples/WireMock.Net.Console.Net472.Classic/App.config
  examples/WireMock.Net.Console.Net472.Classic/WireMock.Net.Console.Net472.Classic.csproj
  examples/WireMock.Net.Console.Net472.Classic/packages.config
  examples/WireMock.Net.Console.Proxy.NETCoreApp2/Program.cs
  examples/WireMock.Net.Console.Proxy.NETCoreApp2/Properties/launchSettings.json
  examples/WireMock.Net.Console.Proxy.NETCoreApp2/WireMock.Net.Console.Proxy.NETCoreApp2.csproj
  examples/WireMock.Net.Console.RequestLogTest/WireMock.Net.Console.RequestLogTest.csproj
  examples/WireMock.Net.Service/WireMock.Net.Service.csproj
  examples/WireMock.Net.Service/packages.config
  examples/WireMock.Net.WebApplication.NETCore2/App.cs
  examples/WireMock.Net.WebApplication.NETCore2/IWireMockService.cs
  examples/WireMock.Net.WebApplication.NETCore2/Program.cs
  examples/WireMock.Net.WebApplication.NETCore2/Properties/launchSettings.json
  examples/WireMock.Net.WebApplication.NETCore2/WireMock.Net.WebApplication.NETCore2.csproj
  examples/WireMock.Net.WebApplication.NETCore2/WireMockService.cs
  examples/WireMock.Net.WebApplication.NETCore2/appsettings.json
  examples/WireMock.Net.WebApplication.NETCore2/libman.json
  examples/WireMock.Net.WebApplication.NETCore2/readme.md
  examples/WireMock.Net.WebApplication.NETCore2/resources/iis-apppool.png
  examples/WireMock.Net.WebApplication.NETCore2/resources/iis-debug.png
  examples/WireMock.Net.WebApplication.NETCore2/resources/iis-wiremock1and2.png
  examples/WireMock.Net.WebApplication.NETCore2/web.config
  src/WireMock.Net.Abstractions/Types/ReplaceNodeOptions.cs
  src/WireMock.Net/RequestBuilders/IBodyRequestBuilder.cs
  src/WireMock.Net/ResponseBuilders/ITransformResponseBuilder.cs
  src/WireMock.Net/ResponseBuilders/Response.cs
  src/WireMock.Net/Serialization/WebhookMapper.cs
  src/WireMock.Net/Server/WireMockServer.ConvertMapping.cs
  src/WireMock.Net/Transformers/Transformer.cs
  src/WireMock.Net/Util/StringUtils.cs
  src/WireMock.Net/WireMock.Net.csproj
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsDateTimeTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsRandomTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithTransformerTests.cs
  test/WireMock.Net.Tests/Serialization/MappingConverterTests.ToMappingModel_WithPriority_ReturnsPriority.verified.txt
  test/WireMock.Net.Tests/Serialization/WebhookMapperTests.WebhookMapper_Map_WebhookModel_BodyAsString_And_UseTransformerIsTrue.verified.txt
  test/WireMock.Net.Tests/Util/StringUtilsTests.cs
Labels: feature

#1043 FindRequestByMappingGuidAsync
  src/WireMock.Net.Abstractions/Admin/Requests/LogEntryModel.cs
  src/WireMock.Net.Abstractions/WireMock.Net.Abstractions.csproj
  src/WireMock.Net.RestClient/IWireMockAdminApi.cs
  src/WireMock.Net/Server/WireMockServer.Admin.cs
  src/WireMock.Net/WireMock.Net.csproj
  test/WireMock.Net.Tests/WireMockAdminApiTests.cs
  test/WireMock.Net.Tests/WireMockServer.Proxy.cs
  test/WireMock.Net.Tests/WireMockServer.Settings.cs
Labels: feature

#1044 WireMockServerSettingsParser
  src/WireMock.Net/Settings/ProxyAndRecordSettings.cs
  src/WireMock.Net/Settings/WireMockServerSettingsParser.cs
Labels: refactor

#1049 Add WithoutHeader to WireMock.FluentAssertions
  src/WireMock.Net.FluentAssertions/Assertions/WireMockAssertions.cs
  test/WireMock.Net.Tests/FluentAssertions/WireMockAssertionsTests.cs
Labels: feature
