Repository wiremock/WireMock.Net, pull requests merged in 2023-10, with the labels that each got.

#1005 Support for xml namespaces in XPathMatcher
  src/WireMock.Net.Abstractions/Admin/Mappings/MatcherModel.cs
  src/WireMock.Net.Abstractions/Admin/Mappings/XmlNamespace.cs
  src/WireMock.Net/Matchers/XPathMatcher.cs
  src/WireMock.Net/Serialization/MatcherMapper.cs
  test/WireMock.Net.Tests/Matchers/XPathMatcherTests.cs
  test/WireMock.Net.Tests/Serialization/MatcherMapperTests.cs
Labels: feature

#1006 Fix RequestMessageParamMatcher : RejectOnMatch
  src/WireMock.Net/Matchers/JsonMatcher.cs
  src/WireMock.Net/Matchers/Request/RequestMessageParamMatcher.cs
  test/WireMock.Net.Tests/WireMockServerTests.WithParam.cs
Labels: bug

#1010 Add unit tests for HttpClient with WebProxy
  examples/WireMock.Net.Console.NETCoreApp3WithCertificate/Program.cs
  src/WireMock.Net/Owin/HostUrlOptions.cs
  src/WireMock.Net/Server/WireMockServer.cs
  test/WireMock.Net.Tests/FluentAssertions/WireMockAssertionsTests.cs
  test/WireMock.Net.Tests/Owin/HostUrlOptionsTests.cs
  test/WireMock.Net.Tests/WireMock.Net.Tests.csproj
  test/WireMock.Net.Tests/WireMockServerTests.cs
  test/WireMock.Net.Tests/cert.pem
Labels: test
