Repository wiremock/WireMock.Net, pull requests merged in 2024-09, with the labels that each got.

#1166 Also update IWireMockMiddlewareOptions when settings are updated via admin interface
  azure-pipelines-ci.yml
  src/WireMock.Net/Owin/WireMockMiddlewareOptionsHelper.cs
  src/WireMock.Net/Server/WireMockServer.Admin.cs
  src/WireMock.Net/Server/WireMockServer.cs
Labels: bug

#1170 Update the .NET Aspire tests
  test/WireMock.Net.Aspire.Tests/DockerUtils.cs
  test/WireMock.Net.Aspire.Tests/Facts/DockerIsRunningInLinuxContainerModeFact.cs
  test/WireMock.Net.Aspire.Tests/IntegrationTests.cs
  test/WireMock.Net.Tests/Facts/IgnoreOnContinuousIntegrationFact.cs
  test/WireMock.Net.Tests/WireMockServerTests.cs
Labels: feature

#1172 Attempt to fix JSON parsing of text/plain content type
  src/WireMock.Net.Abstractions/Models/IBodyDataExtension.cs
  src/WireMock.Net/Http/HttpRequestMessageHelper.cs
  src/WireMock.Net/Owin/Mappers/OwinResponseMapper.cs
  test/WireMock.Net.Tests/Http/HttpRequestMessageHelperTests.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithProxyIntegrationTests.cs
Labels: bug

#1177 Unpin Testcontainers version and upgrade to version 3.10.0
  Directory.Build.props
  src/WireMock.Net.Testcontainers/WireMock.Net.Testcontainers.csproj
Labels: bug

#1178 Upgrade CS-Script to version 4.8.17
  src/WireMock.Net.Matchers.CSharpCode/WireMock.Net.Matchers.CSharpCode.csproj
Labels: feature

#1182 pass in the request when no matching is found to the warn logger
  src/WireMock.Net/Owin/WireMockMiddleware.cs
Labels: feature

#1181 WireMock.Net.Testcontainers: Use 'sheyenrath/wiremock.net-alpine' image as default for Linux
  examples/WireMock.Net.TestcontainersExample/Program.cs
  examples/WireMock.Net.TestcontainersExample/WireMock.Net.TestcontainersExample.csproj
  src/WireMock.Net.Testcontainers/WireMockContainerBuilder.cs
  test/WireMock.Net.Tests/Testcontainers/TestcontainersTests.cs
Labels: feature

#1183 Set <SonarQubeExclude>true</SonarQubeExclude> in test projects
  test/WireMock.Net.Aspire.Tests/WireMock.Net.Aspire.Tests.csproj
  test/WireMock.Net.TUnitTests/WireMock.Net.TUnitTests.csproj
  test/WireMock.Net.Tests/WireMock.Net.Tests.csproj
Labels: test

#1175 Add WireMock.Net.AspNetCore.Middleware
  .github/workflows/ci.yml
  WireMock.Net Solution.sln
  azure-pipelines-ci.yml
  examples/WireMock.Net.WebApplication/Program.cs
  examples/WireMock.Net.WebApplication/Properties/launchSettings.json
  examples/WireMock.Net.WebApplication/WeatherForecast.cs
  examples/WireMock.Net.WebApplication/WireMock.Net.WebApplication.csproj
  examples/WireMock.Net.WebApplication/appsettings.Development.json
  examples/WireMock.Net.WebApplication/appsettings.json
  src/WireMock.Net.AspNetCore.Middleware/AppConstants.cs
  src/WireMock.Net.AspNetCore.Middleware/HttpDelegatingHandler/WireMockDelegationHandler.cs
  src/WireMock.Net.AspNetCore.Middleware/HttpDelegatingHandler/WireMockDelegationHandlerSettings.cs
  src/WireMock.Net.AspNetCore.Middleware/ServiceCollectionExtensions.cs
  src/WireMock.Net.AspNetCore.Middleware/WireMock.Net.AspNetCore.Middleware.csproj
  src/WireMock.Net.AspNetCore.Middleware/WireMockBackgroundService.cs
  src/WireMock.Net.AspNetCore.Middleware/WireMockServerInstance.cs
  test/WireMock.Net.Middleware.Tests/CustomWebApplicationFactory.cs
  test/WireMock.Net.Middleware.Tests/IntegrationTests.cs
  test/WireMock.Net.Middleware.Tests/WireMock.Net.Middleware.Tests.csproj
  test/WireMock.Net.TestWebApplication/Program.cs
  test/WireMock.Net.TestWebApplication/Properties/launchSettings.json
  test/WireMock.Net.TestWebApplication/WireMock.Net.TestWebApplication.csproj
  test/WireMock.Net.TestWebApplication/appsettings.json
Labels: feature

#1185 Throw exception in case WithTransformer is used after WithBodyFromFile
  src/WireMock.Net/ResponseBuilders/Response.WithBody.cs
  src/WireMock.Net/ResponseBuilders/Response.WithTransformer.cs
  src/WireMock.Net/ResponseBuilders/Response.cs
  src/WireMock.Net/Transformers/Transformer.cs
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithTransformerTests.cs
  test/WireMock.Net.Tests/WireMockServerTests.WithTransformer.cs
  test/WireMock.Net.Tests/__admin/mappings/responseWithTransformer.xml
Labels: bug
