Repository wiremock/WireMock.Net, pull requests merged in 2025-05, with the labels that each got.

#1291 Update ProtoBufJsonConverter to fix conflict for 'MessageOptions'
  src/WireMock.Net/WireMock.Net.csproj
Labels: bug

#1288 Update AzureADAuthenticationMatcher to support V2 Azure AAD tokens
  examples/WireMock.Net.Console.Net452.Classic/MainApp.cs
  src/WireMock.Net/Authentication/AzureADAuthenticationMatcher.cs
  src/WireMock.Net/Owin/WireMockMiddleware.cs
  src/WireMock.Net/Server/WireMockServer.cs
  test/WireMock.Net.Tests/Authentication/AzureADAuthenticationMatcherTests.cs
  test/WireMock.Net.Tests/Authentication/MockJwtSecurityTokenHandler.cs
Labels: feature

#1293 Grpc: Fix parsing null value for google.protobuf.Timestamp
  examples/WireMock.Net.Console.GrpcClient/Program.cs
  examples/WireMock.Net.Console.GrpcClient/WireMock.Net.Console.GrpcClient.csproj
  examples/WireMock.Net.Console.GrpcClient/policy.proto
  examples/WireMock.Net.Console.Net452.Classic/MainApp.cs
  src/WireMock.Net/WireMock.Net.csproj
Labels: bug

#1294 Add more tests for WireMockOpenApiParser
  test/WireMock.Net.Tests/OpenApiParser/WireMockOpenApiParserTests.FromText_UsingJson_WithPlainTextExample_ShouldReturnMappings.verified.txt
  test/WireMock.Net.Tests/OpenApiParser/WireMockOpenApiParserTests.FromText_UsingYaml_ShouldReturnMappings.verified.txt
  test/WireMock.Net.Tests/OpenApiParser/WireMockOpenApiParserTests.cs
  test/WireMock.Net.Tests/OpenApiParser/oas-content-example.json
Labels: test

#1296 Content-Type multipart/form-data header should also be proxied
  src/WireMock.Net/Http/ByteArrayContentHelper.cs
  src/WireMock.Net/Http/HttpRequestMessageHelper.cs
  src/WireMock.Net/Http/StringContentHelper.cs
  test/WireMock.Net.Tests/Http/HttpRequestMessageHelperTests.cs
Labels: bug

#1299 Use TinyMapper.Signed
  src/WireMock.Net/WireMock.Net.csproj
Labels: bug

#1297 Fix BodyParser to correctly check for json
  src/WireMock.Net.Abstractions/Models/IBodyDataExtensions.cs
  src/WireMock.Net/Http/HttpRequestMessageHelper.cs
  src/WireMock.Net/Owin/Mappers/OwinResponseMapper.cs
  src/WireMock.Net/Util/BodyParser.cs
  src/WireMock.Net/Util/JsonUtils.cs
  test/WireMock.Net.Tests/Http/HttpRequestMessageHelperTests.cs
  test/WireMock.Net.Tests/Util/BodyParserTests.cs
Labels: bug

#1301 Fix errors when converting response bodies with top-level JSON arrays to C# code
  src/WireMock.Net/Util/CSharpFormatter.cs
Labels: bug

#1303 Add option to provide X509Certificate
  src/WireMock.Net.Minimal/HttpsCertificate/CertificateLoader.cs
  src/WireMock.Net.Minimal/Owin/AspNetCoreSelfHost.NETStandard.cs
  src/WireMock.Net.Minimal/Owin/AspNetCoreSelfHost.NETStandard13.cs
  src/WireMock.Net.Minimal/Owin/IWireMockMiddlewareOptions.cs
  src/WireMock.Net.Minimal/Owin/WireMockMiddlewareOptions.cs
  src/WireMock.Net.Minimal/Owin/WireMockMiddlewareOptionsHelper.cs
  src/WireMock.Net.Minimal/Settings/WireMockCertificateSettings.cs
  src/WireMock.Net.Minimal/Settings/WireMockServerSettings.cs
Labels: feature
