Repository wiremock/WireMock.Net, pull requests merged in 2025-04, with the labels that each got.

#1267 Add extra JsonPartialWildcardMatcher Tests
  src/WireMock.Net/RequestBuilders/Request.WithBody.cs
  test/WireMock.Net.Tests/Matchers/JsonPartialWildcardMatcherTests.cs
  test/WireMock.Net.Tests/WireMockServerTests.WithBody.cs
Labels: test

#1269 Server-Sent Events
  examples/WireMock.Net.Console.Net452.Classic/MainApp.cs
  src/WireMock.Net.Abstractions/Models/IBodyData.cs
  src/WireMock.Net.Abstractions/Types/BlockingQueue.cs
  src/WireMock.Net.Abstractions/Types/BodyType.cs
  src/WireMock.Net.Abstractions/WireMock.Net.Abstractions.csproj
  src/WireMock.Net/Models/BodyData.cs
  src/WireMock.Net/Owin/Mappers/OwinResponseMapper.cs
  src/WireMock.Net/ResponseBuilders/IBodyResponseBuilder.cs
  src/WireMock.Net/ResponseBuilders/Response.WithBody.cs
  test/WireMock.Net.Tests/WireMockServerTests.WithBody.cs
Labels: feature

#1279 Support OpenApi V31
  src/WireMock.Net.OpenApiParser/Extensions/DictionaryExtensions.cs
  src/WireMock.Net.OpenApiParser/Extensions/OpenApiSchemaExtensions.cs
  src/WireMock.Net.OpenApiParser/Extensions/WireMockServerExtensions.cs
  src/WireMock.Net.OpenApiParser/IWireMockOpenApiParser.cs
  src/WireMock.Net.OpenApiParser/Mappers/OpenApiPathsMapper.cs
  src/WireMock.Net.OpenApiParser/Settings/IWireMockOpenApiParserExampleValues.cs
  src/WireMock.Net.OpenApiParser/Settings/WireMockOpenApiParserDynamicExampleValues.cs
  src/WireMock.Net.OpenApiParser/Settings/WireMockOpenApiParserExampleValues.cs
  src/WireMock.Net.OpenApiParser/Types/SchemaType.cs
  src/WireMock.Net.OpenApiParser/Utils/DateTimeUtils.cs
  src/WireMock.Net.OpenApiParser/Utils/ExampleValueGenerator.cs
  src/WireMock.Net.OpenApiParser/WireMock.Net.OpenApiParser.csproj
  src/WireMock.Net.OpenApiParser/WireMockOpenApiParser.cs
  src/WireMock.Net/Server/WireMockServer.OpenApiParser.cs
  src/WireMock.Net/WireMock.Net.csproj
  test/WireMock.Net.Tests/OpenApiParser/WireMockOpenApiParserTests.FromText_ShouldReturnMappings.verified.txt
  test/WireMock.Net.Tests/OpenApiParser/WireMockOpenApiParserTests.cs
  test/WireMock.Net.Tests/OpenApiParser/payroc-openapi-spec.yaml
Labels: feature

#1263 Add ProtoDefinitionHelper.FromDirectory
  WireMock.Net Solution.sln.DotSettings
  src/WireMock.Net/Extensions/StringExtensions.cs
  src/WireMock.Net/Models/ProtoDefinitionData.cs
  src/WireMock.Net/RequestBuilders/Request.WithBodyAsProtoBuf.cs
  src/WireMock.Net/Server/RespondWithAProvider.cs
  src/WireMock.Net/Util/FilePathUtils.cs
  src/WireMock.Net/Util/ProtoDefinitionHelper.cs
  src/WireMock.Net/Util/WireMockProtoFileResolver.cs
  test/WireMock.Net.Tests/Grpc/ProtoDefinitionHelperTests.cs
  test/WireMock.Net.Tests/Grpc/Test/SubFolder/request.proto
  test/WireMock.Net.Tests/Grpc/Test/greet.proto
  test/WireMock.Net.Tests/Grpc/ot/opentelemetry/proto/collector/README.md
  test/WireMock.Net.Tests/Grpc/ot/opentelemetry/proto/collector/logs/v1/logs_service.proto
  test/WireMock.Net.Tests/Grpc/ot/opentelemetry/proto/collector/logs/v1/logs_service_http.yaml
  test/WireMock.Net.Tests/Grpc/ot/opentelemetry/proto/collector/metrics/v1/metrics_service.proto
  test/WireMock.Net.Tests/Grpc/ot/opentelemetry/proto/collector/metrics/v1/metrics_service_http.yaml
  test/WireMock.Net.Tests/Grpc/ot/opentelemetry/proto/collector/profiles/v1development/profiles_service.proto
  test/WireMock.Net.Tests/Grpc/ot/opentelemetry/proto/collector/profiles/v1development/profiles_service_http.yaml
  test/WireMock.Net.Tests/Grpc/ot/opentelemetry/proto/collector/trace/v1/trace_service.proto
  test/WireMock.Net.Tests/Grpc/ot/opentelemetry/proto/collector/trace/v1/trace_service_http.yaml
  test/WireMock.Net.Tests/Grpc/ot/opentelemetry/proto/common/v1/common.proto
  test/WireMock.Net.Tests/Grpc/ot/opentelemetry/proto/logs/v1/logs.proto
  test/WireMock.Net.Tests/Grpc/ot/opentelemetry/proto/metrics/v1/metrics.proto
  test/WireMock.Net.Tests/Grpc/ot/opentelemetry/proto/profiles/v1development/profiles.proto
  test/WireMock.Net.Tests/Grpc/ot/opentelemetry/proto/resource/v1/resource.proto
  test/WireMock.Net.Tests/Grpc/ot/opentelemetry/proto/trace/v1/trace.proto
  test/WireMock.Net.Tests/WireMock.Net.Tests.csproj
Labels: feature

#1282 Use vmImage ubuntu-22.04 and install aspire workload in Azure DevOps CI-CD pipeline
  azure-pipelines-ci.yml
Labels: bug

#1278 changed null check in JSONPathMatcher and JmesPathMatcher to ensure t…
  src/WireMock.Net/Matchers/JSONPathMatcher.cs
  src/WireMock.Net/Matchers/JmesPathMatcher.cs
Labels: bug

#1271 Add HandlebarsSettings
  README.md
  src/WireMock.Net.Abstractions/Types/CustomHandlebarsHelpers.cs
  src/WireMock.Net/Settings/HandlebarsSettings.cs
  src/WireMock.Net/Settings/ProxyAndRecordSettings.cs
  src/WireMock.Net/Settings/ProxyUrlReplaceSettings.cs
  src/WireMock.Net/Settings/SimpleSettingsParser.cs
  src/WireMock.Net/Settings/WebProxySettings.cs
  src/WireMock.Net/Settings/WireMockServerSettings.cs
  src/WireMock.Net/Settings/WireMockServerSettingsParser.cs
  src/WireMock.Net/Transformers/Handlebars/FileHelpers.cs
  src/WireMock.Net/Transformers/Handlebars/WireMockHandlebarsHelpers.cs
  src/WireMock.Net/WireMock.Net.csproj
  test/WireMock.Net.Tests/ResponseBuilders/ResponseWithHandlebarsFileTests.cs
Labels: feature

#1285 Enable support for WireMock Middleware in Hosted Services
  src/WireMock.Net.AspNetCore.Middleware/HttpDelegatingHandler/WireMockDelegationHandler.cs
  test/WireMock.Net.Middleware.Tests/IntegrationTests.cs
  test/WireMock.Net.TestWebApplication/Program.cs
  test/WireMock.Net.TestWebApplication/TaskQueue.cs
  test/WireMock.Net.TestWebApplication/TestBackgroundService.cs
Labels: bug

#1283 Add an launch inspector command to Aspire Dashboard
  azure-pipelines-ci.yml
  examples-Aspire/AspireApp1.AppHost/AspireApp1.AppHost.csproj
  examples-Aspire/AspireApp1.AppHostOriginal/AspireApp1.AppHostOriginal.csproj
  src/WireMock.Net.Aspire/WireMock.Net.Aspire.csproj
  src/WireMock.Net.Aspire/WireMockInspector.cs
  src/WireMock.Net.Aspire/WireMockServerBuilderExtensions.cs
  test/WireMock.Net.Aspire.TestAppHost/WireMock.Net.Aspire.TestAppHost.csproj
  test/WireMock.Net.Aspire.Tests/WireMock.Net.Aspire.Tests.csproj
  test/WireMock.Net.Aspire.Tests/WireMockServerBuilderExtensionsTests.cs
Labels: feature
